feat: add selectUpload config option to ImageBlock
Milkdown/milkdown pull request #1559
Opened 2024-11-13 15:38 UTC by geertplaisier

-   [x] I read the contributing guide 
-   [x] I agree to follow the code of conduct 

## Summary

Currently it is possible to configure an `onUpload` method for the `ImageBlock` component. This allows you to upload the selected image and return the URL. For our application we already have a collection of images available and it would be nice if the user could also select an image instead of always uploading a new one.

For this I added an `selectUpload` method which can be configured for the `ImageBlock` component. This expects a Promise as return value, which works similar to the `onUpload` configuration option but does not pass a file.

## How did you test this change?

Since the implementation for this can vary a lot for each implementation, I added a Storybook story to demonstrate the behavior.

2024-12-10 01:48 UTC, Saul-Mirone commented
This is a little confusing to me. How does the users know what url they should return in the promise if there's no additional parameters?

2024-12-10 22:59 UTC, geertplaisier commented
@Saul-Mirone The only difference between the existing `onUpload` option and the new `selectUpload` is that in the first case the end-user gets a system file picker to select a file from the file system and with the latter you would need to implement some kind of file picker yourself. This could be used for example in a CMS where there is an existing library of images to choose from. Hope this makes sense, if not I can extend the storybook example.

2024-12-15 07:13 UTC, Saul-Mirone commented on packages/components/src/image-block/view/component.ts
> +          <label onpointerdown=${onClickUploader} onclick=${handleUpload} class="uploader" for=${uuid}>
I don't think we should add a new event handler here to handle both `onclick` and `onpointerdown`, a possible solution should be still use `onUpload` without introducting another config. We can pass `event` to the `onUpload` config to let users open their own file picker.

2024-12-15 07:14 UTC, Saul-Mirone requested changes
We should also consider the `image-inline` component in crepe.

2025-05-06 00:55 UTC, closed without merging